sudo: false
language: python
python:
  - 3.5
services:
    - postgresql

branches:
  only:
    - master

env:
  - TRAVIS_NODE_VERSION="6"

install:
  - psql -c 'create database jarbas;' -U postgres
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
  - npm install
  - npm install -g elm
  - pip install -r requirements.txt
  - pip install coveralls

env:
  - DATABASE_URL="postgres://postgres@localhost/jarbas"

before_script:
  - python manage.py migrate
  - travis_wait 45 python manage.py assets build --no-cache
  - python manage.py collectstatic --no-input
  - npm test

script:
  - coverage run manage.py test -v 3

after_success:
  - coveralls
