sudo: false
language: python

python:
  - 3.5

services:
  - postgresql
  - docker

env:
  global:
    - secure: "" # DOCKER_EMAIL
    - secure: "" # DOCKER_USER
    - secure: "" # DOCKER_PASS
    - REPOSITORY: "datasciencebr/jarbas"
    - COMMIT=${TRAVIS_COMMIT::8}

branches:
  only:
    - master

install:
  - psql -c 'create database jarbas;' -U postgres
  - npm install
  - pip install -r requirements.txt
  - pip install coveralls

env:
  - DATABASE_URL="postgres://postgres@localhost/jarbas"

before_script:
  - python manage.py migrate
  - travis_wait python manage.py assets build --no-cache
  - python manage.py collectstatic --no-input

script:
  - coverage run manage.py test -v 3

after_success:
  - coveralls
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPOSITORY:$COMMIT .
  - docker tag $REPOSITORY:$COMMIT $REPOSITORY:$TAG
  - docker tag $REPOSITORY:$COMMIT $REPOSITORY:$TRAVIS_BRANCH
  - docker push $REPOSITORY