---
sudo: false
dist: trusty

language: python
python:
  - 3.5

addons:
    postgresql: "9.6"

before_install:
  - openssl aes-256-cbc -K $encrypted_e9aae701de94_key -iv $encrypted_e9aae701de94_iv -in vault.enc -out vault -d

services:
    - postgresql

env:
  - DATABASE_URL="postgres://postgres@localhost/jarbas"

install:
  - psql -U postgres -c 'create database "jarbas";'
  - nvm install 6
  - nvm use 6
  - npm install
  - pip install -r requirements.txt coveralls
  - pip install ansible dopy

before_script:
  - python manage.py migrate
  - travis_wait 60 npm run assets
  - python manage.py collectstatic --no-input

script:
  - npm test
  - coverage run manage.py test -v 3
  - ansible-playbook -i hosts do.yml --vault-password-file=vault -vvv

after_success:
  - coveralls
